# Generated by Django 4.2.17 on 2026-05-12 17:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import patients.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dmp_id', models.CharField(max_length=20, unique=True)),
                ('prenom', models.CharField(max_length=100)),
                ('nom', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('sexe', models.CharField(choices=[('F', 'Féminin'), ('M', 'Masculin')], max_length=1)),
                ('blood', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], default='O+', max_length=4)),
                ('addr', models.CharField(blank=True, max_length=300)),
                ('tel', models.CharField(blank=True, max_length=20)),
                ('job', models.CharField(blank=True, max_length=100)),
                ('urg', models.CharField(blank=True, max_length=200)),
                ('color', models.CharField(default='#0E7A5F', max_length=10)),
                ('temp_code', models.CharField(default=patients.models.gen_code, max_length=20)),
                ('code', models.CharField(blank=True, max_length=100)),
                ('first_login', models.BooleanField(default=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('ant_chr', models.TextField(blank=True)),
                ('ant_chir', models.TextField(blank=True)),
                ('ant_gyn', models.TextField(blank=True)),
                ('ant_hab', models.TextField(blank=True)),
                ('ant_pere', models.CharField(blank=True, max_length=200)),
                ('ant_mere', models.CharField(blank=True, max_length=200)),
                ('ant_fra', models.CharField(blank=True, max_length=200)),
                ('next_rdv', models.DateField(blank=True, null=True)),
                ('next_motif', models.CharField(blank=True, max_length=200)),
                ('next_urg', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vaccine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField(blank=True, null=True)),
                ('next_date', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('À jour', 'À jour'), ('Rappel dû', 'Rappel dû'), ('Non administré', 'Non administré')], default='À jour', max_length=20)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccines', to='patients.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('allergy_type', models.CharField(choices=[('Médicament', 'Médicament'), ('Alimentaire', 'Alimentaire'), ('Environnemental', 'Environnemental'), ('Contact', 'Contact')], max_length=20)),
                ('reaction', models.CharField(blank=True, max_length=200)),
                ('severity', models.CharField(choices=[('Légère', 'Légère'), ('Modérée-Sévère', 'Modérée-Sévère'), ('Anaphylaxie', 'Anaphylaxie')], default='Légère', max_length=20)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allergies', to='patients.patient')),
            ],
        ),
    ]
