# Generated by Django 4.2.17 on 2026-05-12 17:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('consult_type', models.CharField(choices=[('Consultation ordinaire', 'Consultation ordinaire'), ('Urgence', 'Urgence'), ('Suivi de traitement', 'Suivi de traitement'), ('Bilan de santé', 'Bilan de santé'), ('Consultation prénatale', 'Consultation prénatale'), ('Vaccination', 'Vaccination')], default='Consultation ordinaire', max_length=50)),
                ('motif', models.TextField(blank=True)),
                ('symptoms', models.JSONField(default=list)),
                ('obs_symp', models.TextField(blank=True)),
                ('duration_symp', models.CharField(blank=True, max_length=50)),
                ('vitals', models.JSONField(default=dict)),
                ('exam_cv', models.TextField(blank=True)),
                ('exam_resp', models.TextField(blank=True)),
                ('exam_abdo', models.TextField(blank=True)),
                ('exam_neuro', models.TextField(blank=True)),
                ('exam_orl', models.TextField(blank=True)),
                ('exam_gen', models.TextField(blank=True)),
                ('diag_main', models.CharField(blank=True, max_length=200)),
                ('diag_cim', models.CharField(blank=True, max_length=20)),
                ('diag_severity', models.CharField(blank=True, choices=[('Légère', 'Légère'), ('Modérée', 'Modérée'), ('Sévère', 'Sévère'), ('Critique', 'Critique')], max_length=20)),
                ('diag_d1', models.CharField(blank=True, max_length=200)),
                ('diag_d2', models.CharField(blank=True, max_length=200)),
                ('diag_conclusion', models.TextField(blank=True)),
                ('prescriptions', models.JSONField(default=list)),
                ('rx_notes', models.TextField(blank=True)),
                ('exams_requested', models.JSONField(default=list)),
                ('results', models.JSONField(default=list)),
                ('obs_notes', models.TextField(blank=True)),
                ('next_rdv', models.DateField(blank=True, null=True)),
                ('next_motif', models.CharField(blank=True, max_length=200)),
                ('next_urg', models.CharField(blank=True, max_length=200)),
                ('arret_travail', models.CharField(default='Non', max_length=20)),
                ('refer_spec', models.CharField(blank=True, max_length=100)),
                ('refer_motif', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultations', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='patients.patient')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
